[package]
name = "engine_traits"
version = "0.0.1"
edition = "2018"
publish = false

[features]
protobuf-codec = [
  "raft/protobuf-codec",
  "kvproto/protobuf-codec",
]
prost-codec = [
  "raft/prost-codec",
  "kvproto/prost-codec",
]

[dependencies]
error_code = { path = "../error_code" }
hex = "0.4"
log_wrappers = { path = "../log_wrappers" }
protobuf = "2"
quick-error = "1.2.3"
tikv_alloc = { path = "../tikv_alloc" }
tikv_util = { path = "../tikv_util" }
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "0e23a5baff302a9d7bccd85f8f31e43339c2f2c1" }
kvproto = { git = "https://github.com/pingcap/kvproto.git", default-features = false }
raft = { version = "0.6.0-alpha", default-features = false }